FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# testeMobiCare

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/packages]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "name": "Pontal Praia Hotel",
                "origin":"São Paulo",
                "destiny": "Porto Seguro, Brasil"
                "price": "978",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/aa88664d-2ada-431b-959c-7e56d227d9d7/400x400",
                "url":"/packages/1"
            },
            {
                "id": "2",
                "name": "Waldorf Hotel",
                "origin":"São Paulo",
                "destiny": "Buenos Aires, Argentina"
                "price": "958",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/06542cdf-a11c-4d9e-a144-d23f5d1c18ed/400x400",
                "url":"/packages/2"
            },
            {
                "id": "3",
                "name": "Luxor Hotel and Casino",
                "origin":"São Paulo",
                "destiny": "Las Vegas, Estados Unidos"
                "price": "3029",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/4a493359-80b7-4f16-bfac-f0879fe7e46d/400x400",
                "url":"/packages/3"
            },
            {
                "id": "4",
                "name": "Residence La Genziana",
                "origin":"São Paulo",
                "destiny": "Roma, Itália"
                "price": "2931",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/97ed9f46-5285-4e5f-939c-add941768328/400x400",
                "url":"/packages/4"
            }
            
        ]


## Question [/packages/{id}]

### Question [GET]

+ Parameters
    + id (number)

+ Response 200 (application/json)

        [
            {
                "links": [
                    {
                        "rel": [ "self" ],
                        "href": "/packages/1"
                    }
                ],
                "entities" : {
                    "_links": {
                        "self": { "self": "/packages/1" }
                    },
                    "id": "1",
                    "name": "Pontal Praia Hotel",
                    "origin":"São Paulo",
                    "destiny": "Porto Seguro, Brasil"
                    "price": "978",
                    "days":"7",
                    "images":"https://media.staticontent.com/media/pictures/aa88664d-2ada-431b-959c-7e56d227d9d7/400x400",
                    "url":"/packages/1"
                }
            },
            {
                "links": [
                    {
                        "rel": [ "self" ],
                        "href": "/package/2"
                    }
                ],
                "id": "2",
                "name": "Waldorf Hotel",
                "origin":"São Paulo",
                "destiny": "Buenos Aires, Argentina"
                "price": "958",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/06542cdf-a11c-4d9e-a144-d23f5d1c18ed/400x400",
                "url":"/packages/2"
            },
            {
                "id": "3",
                "name": "Luxor Hotel and Casino",
                "origin":"São Paulo",
                "destiny": "Las Vegas, Estados Unidos"
                "price": "3029",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/4a493359-80b7-4f16-bfac-f0879fe7e46d/400x400",
                "url":"/packages/3"
            },
            {
                "id": "4",
                "name": "Residence La Genziana",
                "origin":"São Paulo",
                "destiny": "Roma, Itália"
                "price": "2931",
                "days":"7",
                "images":"https://media.staticontent.com/media/pictures/97ed9f46-5285-4e5f-939c-add941768328/400x400",
                "url":"/packages/4"
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }